[package]
name = "hello-world-generated"
version = "0.1.0"
authors = ["dawe <dawedawe@posteo.de>"]
license = "MIT"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
